# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import movie_pb2 as movie__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in movie_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MoviePredictionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictRevenue = channel.unary_unary(
                '/movie.MoviePredictionService/PredictRevenue',
                request_serializer=movie__pb2.MovieRequest.SerializeToString,
                response_deserializer=movie__pb2.PredictionResponse.FromString,
                _registered_method=True)


class MoviePredictionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PredictRevenue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoviePredictionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictRevenue': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictRevenue,
                    request_deserializer=movie__pb2.MovieRequest.FromString,
                    response_serializer=movie__pb2.PredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movie.MoviePredictionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('movie.MoviePredictionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MoviePredictionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictRevenue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.MoviePredictionService/PredictRevenue',
            movie__pb2.MovieRequest.SerializeToString,
            movie__pb2.PredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MutexServiceStub:
    """Ricart-Agrawala Mutual Exclusion Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestAccess = channel.unary_unary(
                '/movie.MutexService/RequestAccess',
                request_serializer=movie__pb2.AccessRequest.SerializeToString,
                response_deserializer=movie__pb2.AccessReply.FromString,
                _registered_method=True)


class MutexServiceServicer:
    """Ricart-Agrawala Mutual Exclusion Service
    """

    def RequestAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MutexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAccess,
                    request_deserializer=movie__pb2.AccessRequest.FromString,
                    response_serializer=movie__pb2.AccessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movie.MutexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('movie.MutexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MutexService:
    """Ricart-Agrawala Mutual Exclusion Service
    """

    @staticmethod
    def RequestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.MutexService/RequestAccess',
            movie__pb2.AccessRequest.SerializeToString,
            movie__pb2.AccessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LockServiceStub:
    """=====================================================
    Experiment 5: Deadlock Simulation and Resolution
    =====================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireLock = channel.unary_unary(
                '/movie.LockService/AcquireLock',
                request_serializer=movie__pb2.LockRequest.SerializeToString,
                response_deserializer=movie__pb2.LockReply.FromString,
                _registered_method=True)
        self.ReleaseLock = channel.unary_unary(
                '/movie.LockService/ReleaseLock',
                request_serializer=movie__pb2.LockRequest.SerializeToString,
                response_deserializer=movie__pb2.LockReply.FromString,
                _registered_method=True)


class LockServiceServicer:
    """=====================================================
    Experiment 5: Deadlock Simulation and Resolution
    =====================================================

    """

    def AcquireLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireLock': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLock,
                    request_deserializer=movie__pb2.LockRequest.FromString,
                    response_serializer=movie__pb2.LockReply.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=movie__pb2.LockRequest.FromString,
                    response_serializer=movie__pb2.LockReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movie.LockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('movie.LockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockService:
    """=====================================================
    Experiment 5: Deadlock Simulation and Resolution
    =====================================================

    """

    @staticmethod
    def AcquireLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.LockService/AcquireLock',
            movie__pb2.LockRequest.SerializeToString,
            movie__pb2.LockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.LockService/ReleaseLock',
            movie__pb2.LockRequest.SerializeToString,
            movie__pb2.LockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
