# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: movie.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'movie.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovie.proto\x12\x05movie\"\xac\x02\n\x0cMovieRequest\x12\r\n\x05genre\x18\x01 \x01(\t\x12\x16\n\x0e\x62udget_million\x18\x02 \x01(\x02\x12\x14\n\x0crelease_year\x18\x03 \x01(\x05\x12\x13\n\x0bruntime_min\x18\x04 \x01(\x02\x12\x15\n\rcritic_rating\x18\x05 \x01(\x02\x12\x17\n\x0f\x61udience_rating\x18\x06 \x01(\x02\x12\x18\n\x10review_sentiment\x18\x07 \x01(\x02\x12\x15\n\rreview_volume\x18\x08 \x01(\x05\x12\x12\n\nstar_power\x18\t \x01(\x02\x12\x19\n\x11social_media_buzz\x18\n \x01(\x05\x12\x1f\n\x17marketing_spend_million\x18\x0b \x01(\x02\x12\x19\n\x11lamport_timestamp\x18\x0c \x01(\x03\"[\n\x12PredictionResponse\x12\x19\n\x11predicted_revenue\x18\x01 \x01(\x02\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x03 \x01(\x03\"3\n\rAccessRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"1\n\x0b\x41\x63\x63\x65ssReply\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"H\n\x0bLockRequest\x12\x13\n\x0bresource_id\x18\x01 \x01(\t\x12\x11\n\tholder_id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\"-\n\tLockReply\x12\x0f\n\x07granted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2Z\n\x16MoviePredictionService\x12@\n\x0ePredictRevenue\x12\x13.movie.MovieRequest\x1a\x19.movie.PredictionResponse2I\n\x0cMutexService\x12\x39\n\rRequestAccess\x12\x14.movie.AccessRequest\x1a\x12.movie.AccessReply2w\n\x0bLockService\x12\x33\n\x0b\x41\x63quireLock\x12\x12.movie.LockRequest\x1a\x10.movie.LockReply\x12\x33\n\x0bReleaseLock\x12\x12.movie.LockRequest\x1a\x10.movie.LockReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movie_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVIEREQUEST']._serialized_start=23
  _globals['_MOVIEREQUEST']._serialized_end=323
  _globals['_PREDICTIONRESPONSE']._serialized_start=325
  _globals['_PREDICTIONRESPONSE']._serialized_end=416
  _globals['_ACCESSREQUEST']._serialized_start=418
  _globals['_ACCESSREQUEST']._serialized_end=469
  _globals['_ACCESSREPLY']._serialized_start=471
  _globals['_ACCESSREPLY']._serialized_end=520
  _globals['_LOCKREQUEST']._serialized_start=522
  _globals['_LOCKREQUEST']._serialized_end=594
  _globals['_LOCKREPLY']._serialized_start=596
  _globals['_LOCKREPLY']._serialized_end=641
  _globals['_MOVIEPREDICTIONSERVICE']._serialized_start=643
  _globals['_MOVIEPREDICTIONSERVICE']._serialized_end=733
  _globals['_MUTEXSERVICE']._serialized_start=735
  _globals['_MUTEXSERVICE']._serialized_end=808
  _globals['_LOCKSERVICE']._serialized_start=810
  _globals['_LOCKSERVICE']._serialized_end=929
# @@protoc_insertion_point(module_scope)
