# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\traft_demo\"1\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\"/\n\tVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"3\n\x10HeartbeatRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\"/\n\x0eHeartbeatReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x93\x01\n\x0bRaftService\x12;\n\x0bRequestVote\x12\x16.raft_demo.VoteRequest\x1a\x14.raft_demo.VoteReply\x12G\n\rAppendEntries\x12\x1b.raft_demo.HeartbeatRequest\x1a\x19.raft_demo.HeartbeatReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=25
  _globals['_VOTEREQUEST']._serialized_end=74
  _globals['_VOTEREPLY']._serialized_start=76
  _globals['_VOTEREPLY']._serialized_end=123
  _globals['_HEARTBEATREQUEST']._serialized_start=125
  _globals['_HEARTBEATREQUEST']._serialized_end=176
  _globals['_HEARTBEATREPLY']._serialized_start=178
  _globals['_HEARTBEATREPLY']._serialized_end=225
  _globals['_RAFTSERVICE']._serialized_start=228
  _globals['_RAFTSERVICE']._serialized_end=375
# @@protoc_insertion_point(module_scope)
