# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replica.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'replica.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreplica.proto\x12\reventual_demo\"^\n\x0bValueUpdate\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x03 \x01(\x05\x12\x16\n\x0eorigin_replica\x18\x04 \x01(\t\"G\n\x07SaveAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07replica\x18\x02 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x03 \x01(\x05\"\x19\n\nValueQuery\x12\x0b\n\x03key\x18\x01 \x01(\t\"]\n\nValueState\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x03 \x01(\x05\x12\x16\n\x0eorigin_replica\x18\x04 \x01(\t2\xd5\x01\n\x0eReplicaService\x12?\n\tSaveValue\x12\x1a.eventual_demo.ValueUpdate\x1a\x16.eventual_demo.SaveAck\x12@\n\nSyncUpdate\x12\x1a.eventual_demo.ValueUpdate\x1a\x16.eventual_demo.SaveAck\x12@\n\x08GetValue\x12\x19.eventual_demo.ValueQuery\x1a\x19.eventual_demo.ValueStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replica_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALUEUPDATE']._serialized_start=32
  _globals['_VALUEUPDATE']._serialized_end=126
  _globals['_SAVEACK']._serialized_start=128
  _globals['_SAVEACK']._serialized_end=199
  _globals['_VALUEQUERY']._serialized_start=201
  _globals['_VALUEQUERY']._serialized_end=226
  _globals['_VALUESTATE']._serialized_start=228
  _globals['_VALUESTATE']._serialized_end=321
  _globals['_REPLICASERVICE']._serialized_start=324
  _globals['_REPLICASERVICE']._serialized_end=537
# @@protoc_insertion_point(module_scope)
