# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import replica_pb2 as replica__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in replica_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicaServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveValue = channel.unary_unary(
                '/eventual_demo.ReplicaService/SaveValue',
                request_serializer=replica__pb2.ValueUpdate.SerializeToString,
                response_deserializer=replica__pb2.SaveAck.FromString,
                _registered_method=True)
        self.SyncUpdate = channel.unary_unary(
                '/eventual_demo.ReplicaService/SyncUpdate',
                request_serializer=replica__pb2.ValueUpdate.SerializeToString,
                response_deserializer=replica__pb2.SaveAck.FromString,
                _registered_method=True)
        self.GetValue = channel.unary_unary(
                '/eventual_demo.ReplicaService/GetValue',
                request_serializer=replica__pb2.ValueQuery.SerializeToString,
                response_deserializer=replica__pb2.ValueState.FromString,
                _registered_method=True)


class ReplicaServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SaveValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveValue,
                    request_deserializer=replica__pb2.ValueUpdate.FromString,
                    response_serializer=replica__pb2.SaveAck.SerializeToString,
            ),
            'SyncUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncUpdate,
                    request_deserializer=replica__pb2.ValueUpdate.FromString,
                    response_serializer=replica__pb2.SaveAck.SerializeToString,
            ),
            'GetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValue,
                    request_deserializer=replica__pb2.ValueQuery.FromString,
                    response_serializer=replica__pb2.ValueState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eventual_demo.ReplicaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eventual_demo.ReplicaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicaService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventual_demo.ReplicaService/SaveValue',
            replica__pb2.ValueUpdate.SerializeToString,
            replica__pb2.SaveAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventual_demo.ReplicaService/SyncUpdate',
            replica__pb2.ValueUpdate.SerializeToString,
            replica__pb2.SaveAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/eventual_demo.ReplicaService/GetValue',
            replica__pb2.ValueQuery.SerializeToString,
            replica__pb2.ValueState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
