// =====================================================
// Existing Movie Prediction Service
// Experiment 2 / 3
// =====================================================

syntax = "proto3";

package movie;

service MoviePredictionService {
  rpc PredictRevenue (MovieRequest) returns (PredictionResponse);
}

message MovieRequest {
  string genre = 1;

  float budget_million = 2;
  int32 release_year = 3;
  float runtime_min = 4;
  float critic_rating = 5;
  float audience_rating = 6;
  float review_sentiment = 7;
  int32 review_volume = 8;
  float star_power = 9;
  int32 social_media_buzz = 10;
  float marketing_spend_million = 11;

  int64 lamport_timestamp = 12;
}

message PredictionResponse {
  float predicted_revenue = 1;
  string message = 2;
  int64 lamport_timestamp = 3;
}


// =====================================================
// Experiment 4: Ricart-Agrawala Mutual Exclusion
// =====================================================

service MutexService {
    rpc RequestAccess (AccessRequest) returns (AccessReply);
}

message AccessRequest {
    int32 node_id = 1;
    int64 timestamp = 2;
}

message AccessReply {
    int32 node_id = 1;
    int64 timestamp = 2;
}


// =====================================================
// Experiment 5: Deadlock Simulation and Resolution
// =====================================================

service LockService {

    rpc AcquireLock (LockRequest) returns (LockReply);

    rpc ReleaseLock (LockRequest) returns (LockReply);

}

message LockRequest {

    string resource_id = 1;

    int32 holder_id = 2;

    int32 timestamp = 3;

}

message LockReply {

    bool granted = 1;

    string message = 2;

}